"""
Seed Media Assets Script for BGMI Intel Media Hub
Populates bgmi_intel.db with 50+ Pinterest-grade high-quality BGMI & PUBG Mobile images,
wallpapers, player portraits, team graphics, X-Suits, weapons, and tournament moments.
"""

import sys
import os
import datetime
import uuid

sys.path.insert(0, os.path.dirname(__file__))

from models.database import engine, SessionLocal, Base
from models.schema_models import MediaAsset

# Ensure all tables exist
Base.metadata.create_all(bind=engine)

def seed_media():
    # Re-create media_assets table to ensure new columns (like_count, pinterest_url) exist
    try:
        MediaAsset.__table__.drop(bind=engine, checkfirst=True)
        MediaAsset.__table__.create(bind=engine, checkfirst=True)
        print("[Seed Media] Re-created media_assets table schema.")
    except Exception as ex:
        print("[Seed Media] Notice on table recreation:", ex)

    db = SessionLocal()
    try:

        base_time = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=30)
        
        # 50+ High quality Pinterest-grade BGMI & PUBG Mobile Media Assets
        assets = [
            # =========================================================================
            # WALLPAPERS & PINTEREST AESTHETICS (4K / 2K)
            # =========================================================================
            {
                "title": "Level 3 Helmet & AWM Neon Energy Aura Wallpaper",
                "description": "Pinterest Trending 4K BGMI aesthetic wallpaper featuring the icon Level 3 Helmet with glowing orange energy aura and AWM sniper rifle.",
                "image_url": "/bg_login.png",
                "thumbnail_url": "/bg_login.png",
                "category": "Wallpapers",
                "tags": "Wallpaper, 4K, Level 3 Helmet, AWM, Neon, Dark, Gaming, Pinterest, Background",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "8.4 MB",
                "file_format": "PNG",
                "view_count": 58420,
                "download_count": 24900,
                "featured": True,
                "source": "BGMI Intel Media Studio",
                "license": "Free Personal Use"
            },
            {
                "title": "Cyberpunk Stadium & BGMI Air Drop Crate 4K",
                "description": "Futuristic desktop wallpaper featuring a red glow Air Drop crate landing inside a neon cyberpunk esports arena.",
                "image_url": "/bg_signup.png",
                "thumbnail_url": "/bg_signup.png",
                "category": "Wallpapers",
                "tags": "Wallpaper, 4K, Cyberpunk, Air Drop, Crate, Neon, Arena, Desktop, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "7.9 MB",
                "file_format": "PNG",
                "view_count": 42100,
                "download_count": 18200,
                "featured": True,
                "source": "Pinterest BGMI Hub",
                "license": "Free Personal Use"
            },
            {
                "title": "Golden Level 3 Helmet Mobile 9:16 Lockscreen",
                "description": "Pinterest Top Mobile Lockscreen: Metallic gold Level 3 Helmet with dark OLED background designed for smartphones.",
                "image_url": "/helmet_logo.png",
                "thumbnail_url": "/helmet_logo.png",
                "category": "Wallpapers",
                "tags": "Mobile, Lockscreen, 9:16, Gold Helmet, Level 3, OLED, Wallpaper, Pinterest",
                "resolution": "Full HD",
                "width": 1080,
                "height": 1920,
                "orientation": "Portrait",
                "file_size": "1.8 MB",
                "file_format": "PNG",
                "view_count": 34900,
                "download_count": 15400,
                "featured": False,
                "source": "Pinterest BGMI Mobile",
                "license": "Free Personal Use"
            },
            {
                "title": "Pharaoh X-Suit Golden Dynasty 4K Wallpaper",
                "description": "Exclusive Pinterest aesthetic artwork of the upgraded Golden Pharaoh X-Suit holding the Anubis Scythe weapon.",
                "image_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "Pharaoh, X-Suit, Gold, BGMI, Anubis, Legendary, Outfit, 4K, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.2 MB",
                "file_format": "JPG",
                "view_count": 62400,
                "download_count": 28100,
                "featured": True,
                "source": "Pinterest BGMI X-Suits",
                "license": "Editorial Use"
            },
            {
                "title": "Ignis X-Suit Flame Warden Aesthetic Art",
                "description": "Fiery Pinterest aesthetic render of the Ignis X-Suit with burning phoenix wings and magma trails.",
                "image_url": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "Ignis, X-Suit, Fire, Flame, BGMI, Wings, Legendary, Wallpaper, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.8 MB",
                "file_format": "JPG",
                "view_count": 48900,
                "download_count": 21300,
                "featured": True,
                "source": "Pinterest PUBG Mobile",
                "license": "Editorial"
            },
            {
                "title": "Silvanus Forest Sovereign X-Suit Portrait",
                "description": "Mystical Pinterest portrait of the Silvanus X-Suit adorned with enchanted emerald leaves and spirit bow.",
                "image_url": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1080&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80",
                "category": "Wallpapers",
                "tags": "Silvanus, Forest, X-Suit, Emerald, Bow, Portrait, Phone, Pinterest",
                "resolution": "2K",
                "width": 1440,
                "height": 2560,
                "orientation": "Portrait",
                "file_size": "4.1 MB",
                "file_format": "JPG",
                "view_count": 29800,
                "download_count": 12400,
                "featured": False,
                "source": "Pinterest BGMI Wallpapers",
                "license": "Free Personal Use"
            },
            {
                "title": "M416 Glacier Max Level Upgrade Aesthetic",
                "description": "High resolution shot of the iconic M416 Glacier skin at Level 7 with crystal loot crate and hit effect particle trail.",
                "image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "M416, Glacier, Gun Skin, Upgrade, Hit Effect, Ice, Crystal, BGMI, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "7.3 MB",
                "file_format": "PNG",
                "view_count": 78900,
                "download_count": 36200,
                "featured": True,
                "source": "Pinterest BGMI Skins",
                "license": "Editorial"
            },
            {
                "title": "AWM Dragon Lore Mythic Sniper Rifle",
                "description": "Detailed Pinterest close-up render of the AWM Dragon Lore sniper rifle resting on a high-terrain crag in Miramar.",
                "image_url": "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "AWM, Sniper, Dragon Lore, Gun Skin, Weapon, BGMI, Miramar, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.7 MB",
                "file_format": "JPG",
                "view_count": 39500,
                "download_count": 17800,
                "featured": False,
                "source": "Pinterest Weapon Skins",
                "license": "Editorial"
            },
            {
                "title": "AKM Seven Seas Pirate Captain Upgrade",
                "description": "Pirate-themed AKM Seven Seas skin with golden compass emblem and nautical kill message animation backdrop.",
                "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "AKM, Seven Seas, Pirate, Weapon, Gun Skin, BGMI, Upgrade, Pinterest",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "4.5 MB",
                "file_format": "JPG",
                "view_count": 31200,
                "download_count": 13900,
                "featured": False,
                "source": "Pinterest BGMI Weapons",
                "license": "Editorial"
            },
            {
                "title": "Flare Gun Red Signal Beam Night Sky",
                "description": "Atmospheric Pinterest night shot of a Flare Gun firing a bright crimson beacon high above Erangel Sosnovka Military Base.",
                "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "Flare Gun, Red Light, Night, Erangel, Air Drop, Signal, Wallpaper, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.4 MB",
                "file_format": "JPG",
                "view_count": 45800,
                "download_count": 19600,
                "featured": True,
                "source": "Pinterest BGMI Night Shots",
                "license": "Free Personal Use"
            },
            {
                "title": "Neon Ghillie Suit Sniper Stealth Mode",
                "description": "Grassy Ghillie suit sniper blending in the wheat fields of Gatka with suppressed sniper scope overlay.",
                "image_url": "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "Ghillie Suit, Stealth, Sniper, Erangel, Wheat Field, Scope, Pinterest",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "3.9 MB",
                "file_format": "JPG",
                "view_count": 27400,
                "download_count": 11200,
                "featured": False,
                "source": "Pinterest BGMI Tactics",
                "license": "Free Personal Use"
            },

            # =========================================================================
            # ESPORTS & TOURNAMENTS (BGIS, BMPS, BGMS, PMGC)
            # =========================================================================
            {
                "title": "BGIS 2026 Grand Finals Trophy Ceremony",
                "description": "The dramatic moment when the BGIS 2026 champions lifted the trophy at the packed stadium in Delhi.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581953220-bmps2026.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581953220-bmps2026.webp",
                "category": "Esports",
                "tags": "BGIS2026, Trophy, Finals, Krafton, Champions, Stage, LAN",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "4.2 MB",
                "file_format": "WEBP",
                "view_count": 18420,
                "download_count": 5210,
                "featured": True,
                "source": "Official Krafton BGMI Esports",
                "license": "Editorial Use"
            },
            {
                "title": "BMPS 2026 Main Stage & Arena Light Show",
                "description": "Panoramic wide shot of the electrifying main stage light show during the BMPS 2026 opening ceremony.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581091732-Estats_logo.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581091732-Estats_logo.webp",
                "category": "Esports",
                "tags": "BMPS2026, Stage, Arena, Esports, Tournament, Opening Ceremony, Light Show",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.1 MB",
                "file_format": "PNG",
                "view_count": 14200,
                "download_count": 3980,
                "featured": True,
                "source": "Nodwin Gaming Media",
                "license": "Editorial"
            },
            {
                "title": "BGMS Season 3 LAN Finals Crowd Atmosphere",
                "description": "Crowd cheering and live caster reaction during the final match clutch at BGMI Master Series Season 3 on Star Sports.",
                "image_url": "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80",
                "category": "Esports",
                "tags": "BGMS, Star Sports, Arena, Crowd, LAN Finals, Esports, Casters",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "2.8 MB",
                "file_format": "JPG",
                "view_count": 9850,
                "download_count": 2410,
                "featured": True,
                "source": "Star Sports Esports",
                "license": "Public Press"
            },
            {
                "title": "PMGC Global Championship Main Stage Arena",
                "description": "Global esports stadium setup featuring 16 team pods and huge LED sky screens during PUBG Mobile Global Championship.",
                "image_url": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80",
                "category": "Esports",
                "tags": "PMGC, Global Championship, World Finals, Arena, Pods, Stage, International",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.5 MB",
                "file_format": "JPG",
                "view_count": 32400,
                "download_count": 14200,
                "featured": True,
                "source": "PUBG Mobile Esports Global",
                "license": "Editorial"
            },
            {
                "title": "Winner Winner Chicken Dinner Live Celebration",
                "description": "Confetti shower moment as the winning squad stands under the WWCD banner at the indoor esports coliseum.",
                "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80",
                "category": "Esports",
                "tags": "WWCD, Winner, Chicken Dinner, Celebration, Confetti, Stage, Team, BGIS",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "4.6 MB",
                "file_format": "JPG",
                "view_count": 21800,
                "download_count": 8900,
                "featured": False,
                "source": "Krafton Esports Press",
                "license": "Editorial"
            },

            # =========================================================================
            # TEAMS & ROSTERS (GODLIKE, SOUL, ORANGUTAN, XSPARK, ENTITY, CARNIVAL)
            # =========================================================================
            {
                "title": "GodLike Esports Official Roster 2026",
                "description": "Official team banner shot featuring Jonathan, ClutchGod, ZGOD, and Admino in GodLike jersey.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785582003005-GODLIKE-ESPORTS.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785582003005-GODLIKE-ESPORTS.webp",
                "category": "Teams",
                "tags": "GodLike, Team Photo, Jonathan, Jersey, 2026 Roster, Esports",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "3.9 MB",
                "file_format": "WEBP",
                "view_count": 28900,
                "download_count": 9450,
                "featured": True,
                "source": "GodLike Esports Media",
                "license": "Official Press Kit"
            },
            {
                "title": "Team SouL Victory Celebration & WWCD Moment",
                "description": "Team SouL players celebrating after securing back-to-back Chicken Dinners at BMPS 2026.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786964971805-Team-Soul.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786964971805-Team-Soul.webp",
                "category": "Teams",
                "tags": "Team SouL, SouL, WWCD, Manya, Nakul, Rony, Celebration, Trophy",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "4.5 MB",
                "file_format": "JPG",
                "view_count": 31200,
                "download_count": 11800,
                "featured": True,
                "source": "iQOO SouL Media",
                "license": "Official Press Kit"
            },
            {
                "title": "Orangutan Esports Team Crest 4K Vector",
                "description": "High-definition 4K vector asset of the Orangutan Esports logo for wallpaper and broadcast lower thirds.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786965109628-Orangutan.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786965109628-Orangutan.webp",
                "category": "Teams",
                "tags": "Orangutan, Logo, Vector, 4K, Branding, Team Media, PNG",
                "resolution": "4K",
                "width": 3840,
                "height": 3840,
                "orientation": "Square",
                "file_size": "1.8 MB",
                "file_format": "PNG",
                "view_count": 6400,
                "download_count": 1920,
                "featured": False,
                "source": "Orangutan Esports",
                "license": "Brand Media Kit"
            },
            {
                "title": "Team XSpark BGIS Championship Squad",
                "description": "ScoutOP leading Team XSpark squad onstage after taking top honors in BGIS semifinal standings.",
                "image_url": "https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=800&q=80",
                "category": "Teams",
                "tags": "Team XSpark, Scout, TX, Roster, BGIS, Champions, Stage",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.2 MB",
                "file_format": "JPG",
                "view_count": 27800,
                "download_count": 10500,
                "featured": True,
                "source": "Team XSpark Official",
                "license": "Press Kit"
            },
            {
                "title": "GENESIS Esports Stage Lineup",
                "description": "GENESIS Esports line up on stage for team introductions prior to match start.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785581996850-GENESIS-ESPORTS.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785581996850-GENESIS-ESPORTS.webp",
                "category": "Teams",
                "tags": "GENESIS, Stage, Roster, BGIS, Player Lineup",
                "resolution": "Full HD",
                "width": 1920,
                "height": 1080,
                "orientation": "Landscape",
                "file_size": "1.9 MB",
                "file_format": "JPG",
                "view_count": 4820,
                "download_count": 1130,
                "featured": False,
                "source": "EsportStats Media",
                "license": "Editorial"
            },
            {
                "title": "Global Esports Crimson Warriors Roster",
                "description": "Official Global Esports BGMI roster portrait in dark crimson jerseys.",
                "image_url": "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
                "category": "Teams",
                "tags": "Global Esports, GE, Roster, Jersey, Crimson, Team",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "3.7 MB",
                "file_format": "JPG",
                "view_count": 15400,
                "download_count": 5900,
                "featured": False,
                "source": "Global Esports Press",
                "license": "Brand Media Kit"
            },
            {
                "title": "Carnival Gaming Roster Launch Graphic",
                "description": "Carnival Gaming official BGMI pro lineup visual featuring Hector and Omega.",
                "image_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80",
                "category": "Teams",
                "tags": "Carnival Gaming, Hector, Omega, Roster, Launch, Graphic",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "4.9 MB",
                "file_format": "JPG",
                "view_count": 18200,
                "download_count": 6400,
                "featured": False,
                "source": "Carnival Gaming",
                "license": "Press Kit"
            },

            # =========================================================================
            # PLAYERS & PRO STARS (JONATHAN, SCOUT, MANYA, GOBLIN, ADMINO, ZGOD)
            # =========================================================================
            {
                "title": "JONATHAN — The Assaulter Supreme Portrait",
                "description": "Studio portrait of Jonathan Amaral wearing the 2026 GodLike pro jersey.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785582003005-GODLIKE-ESPORTS.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1785582003005-GODLIKE-ESPORTS.webp",
                "category": "Players",
                "tags": "JONATHAN, Jonathan Amaral, GodLike, Portrait, Assaulter, MVP",
                "resolution": "4K",
                "width": 2160,
                "height": 3840,
                "orientation": "Portrait",
                "file_size": "3.4 MB",
                "file_format": "PNG",
                "view_count": 42100,
                "download_count": 14900,
                "featured": True,
                "source": "GodLike Media Studio",
                "license": "Editorial"
            },
            {
                "title": "ScoutOP Intense Gaming Setup & Focus",
                "description": "High resolution shot of ScoutOP in action during live stream tournament match.",
                "image_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80",
                "category": "Players",
                "tags": "Scout, ScoutOP, Team XSpark, Streamer, Assaulter, Headset",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.6 MB",
                "file_format": "JPG",
                "view_count": 49800,
                "download_count": 18400,
                "featured": True,
                "source": "ScoutOP Official",
                "license": "Press Kit"
            },
            {
                "title": "Goblin 1v4 Clutch Reaction Moment",
                "description": "High-speed camera capture of Goblin's intense focus during a game-winning 1v4 clutch match.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786964971805-Team-Soul.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/teamlogos/1786964971805-Team-Soul.webp",
                "category": "Players",
                "tags": "Goblin, SouL, Clutch, Reaction, Fragger, High Motion",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "2.2 MB",
                "file_format": "JPG",
                "view_count": 19400,
                "download_count": 5800,
                "featured": True,
                "source": "Nodwin Tournament Media",
                "license": "Editorial"
            },
            {
                "title": "Manya Mastermind IGL Tactical Callouts",
                "description": "Team SouL captain Manya giving circle rotation callouts on map tablet during LAN finals.",
                "image_url": "https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1534423861386-85a16f5d13fd?auto=format&fit=crop&w=800&q=80",
                "category": "Players",
                "tags": "Manya, IGL, SouL, Captain, Callout, Tactical, Map",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "3.1 MB",
                "file_format": "JPG",
                "view_count": 14800,
                "download_count": 5100,
                "featured": False,
                "source": "SouL Media",
                "license": "Editorial"
            },
            {
                "title": "Admino GodLike Precision Sniper Focus",
                "description": "Admino adjusting scope zeroing on AWM during Miramar long range engagements.",
                "image_url": "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=800&q=80",
                "category": "Players",
                "tags": "Admino, GodLike, Sniper, Focus, Scope, Miramar",
                "resolution": "Full HD",
                "width": 1920,
                "height": 1080,
                "orientation": "Landscape",
                "file_size": "2.4 MB",
                "file_format": "JPG",
                "view_count": 11200,
                "download_count": 3900,
                "featured": False,
                "source": "GodLike Media",
                "license": "Editorial"
            },

            # =========================================================================
            # MAP LANDSCAPES & IN-GAME ART (ERANGEL, MIRAMAR, RONDO, SANHOK, NUSA)
            # =========================================================================
            {
                "title": "Erangel 3.2 Tactical Overview Map Artwork",
                "description": "Ultra-detailed 4K tactical map overview of Erangel featuring drop zones Pochinki, Yasnaya, and Sosnovka.",
                "image_url": "/map_erangel.png",
                "thumbnail_url": "/map_erangel.png",
                "category": "BGMI",
                "tags": "Erangel, Map, Tactical, Pochinki, Drop Zone, BGMI 3.2, Artwork",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.8 MB",
                "file_format": "PNG",
                "view_count": 15600,
                "download_count": 6700,
                "featured": True,
                "source": "Krafton BGMI Design",
                "license": "Official Asset"
            },
            {
                "title": "Miramar Desert Battlefield Sunset Visual",
                "description": "Cinematic screenshot of Miramar desert mountains during golden hour in BGMI.",
                "image_url": "/map_miramar.png",
                "thumbnail_url": "/map_miramar.png",
                "category": "BGMI",
                "tags": "Miramar, Desert, Sunset, Pecado, Wallpaper, Gameplay",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.9 MB",
                "file_format": "PNG",
                "view_count": 12800,
                "download_count": 4890,
                "featured": False,
                "source": "BGMI Official",
                "license": "Official Asset"
            },
            {
                "title": "Rondo Bamboo City Landmark Concept Art",
                "description": "High resolution environment render of Rondo Jadena City and NEOX Factory.",
                "image_url": "/map_rondo.png",
                "thumbnail_url": "/map_rondo.png",
                "category": "BGMI",
                "tags": "Rondo, Jadena City, NEOX, Concept Art, Map, BGMI",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "7.1 MB",
                "file_format": "PNG",
                "view_count": 11200,
                "download_count": 4150,
                "featured": False,
                "source": "Krafton Development Studio",
                "license": "Official Asset"
            },
            {
                "title": "Sanhok Bootcamp Rainforest Combat Heatmap",
                "description": "Atmospheric tropical rainforest concept of Sanhok Bootcamp river bridge conflict zone.",
                "image_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
                "category": "BGMI",
                "tags": "Sanhok, Bootcamp, Rainforest, Bridge, Combat, BGMI",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.3 MB",
                "file_format": "JPG",
                "view_count": 18900,
                "download_count": 7200,
                "featured": True,
                "source": "Pinterest BGMI Landscapes",
                "license": "Free Personal Use"
            },
            {
                "title": "Vikendi Snow Park & Castle Fortress Visual",
                "description": "Snowy peak vista of Vikendi Castle surrounded by frozen ice sheet and snowmobiles.",
                "image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
                "category": "BGMI",
                "tags": "Vikendi, Snow, Castle, Fortress, Map, BGMI",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "4.8 MB",
                "file_format": "JPG",
                "view_count": 14300,
                "download_count": 5100,
                "featured": False,
                "source": "Pinterest BGMI Landscapes",
                "license": "Free Personal Use"
            },

            # =========================================================================
            # WEAPONS, VEHICLES & AIR DROPS
            # =========================================================================
            {
                "title": "Monster Truck & Buggy Sand Drift in Miramar",
                "description": "Action shot of off-road Monster Truck drifting through Pecado sand dunes under artillery flare.",
                "image_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
                "category": "BGMI",
                "tags": "Vehicle, Buggy, Monster Truck, Miramar, Drift, Dune",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "5.7 MB",
                "file_format": "JPG",
                "view_count": 22100,
                "download_count": 8300,
                "featured": True,
                "source": "Pinterest BGMI Vehicles",
                "license": "Free Personal Use"
            },
            {
                "title": "UAZ Armored Convoy Bridge Blockade",
                "description": "Tactical 4-UAZ squad blockade setup on Military Bridge holding zone rotation.",
                "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
                "category": "BGMI",
                "tags": "UAZ, Convoy, Bridge, Blockade, Tactical, Squad, Erangel",
                "resolution": "2K",
                "width": 2560,
                "height": 1440,
                "orientation": "Landscape",
                "file_size": "4.2 MB",
                "file_format": "JPG",
                "view_count": 17600,
                "download_count": 6400,
                "featured": False,
                "source": "Pinterest BGMI Tactics",
                "license": "Free Personal Use"
            },
            {
                "title": "Beryl M762 Deadly Precision Spray Art",
                "description": "Up-close gunsmith angle of the Beryl M762 rifle with compensator and angled foregrip.",
                "image_url": "https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=800&q=80",
                "category": "Wallpapers",
                "tags": "Beryl M762, Gun, Weapon, Spray, Attachments, 4K, Pinterest",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.1 MB",
                "file_format": "JPG",
                "view_count": 31900,
                "download_count": 12700,
                "featured": False,
                "source": "Pinterest Weapon Renders",
                "license": "Free Personal Use"
            },

            # =========================================================================
            # EVENTS & OFFICIAL PROMOTIONAL POSTERS
            # =========================================================================
            {
                "title": "BGIS 2026 Official Launch Announcement Poster",
                "description": "Official announcement banner for BGIS 2026 boasting INR 3.5 Crore prize pool.",
                "image_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581953220-bmps2026.webp",
                "thumbnail_url": "https://cdn.jsdelivr.net/gh/esportstatsdata/media-storage@main/images/shivam/general/1785581953220-bmps2026.webp",
                "category": "Events",
                "tags": "BGIS2026, Launch, Poster, Announcement, Krafton, Prize Pool",
                "resolution": "Full HD",
                "width": 1920,
                "height": 1080,
                "orientation": "Landscape",
                "file_size": "2.1 MB",
                "file_format": "WEBP",
                "view_count": 8900,
                "download_count": 2100,
                "featured": False,
                "source": "Krafton India",
                "license": "Press Kit"
            },
            {
                "title": "BGMI 3.2 Update Mecha Fusion Theme Banner",
                "description": "Key art poster introducing Mecha Leviathan vehicles and flying jetpacks in BGMI Version 3.2.",
                "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1920&q=80",
                "thumbnail_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
                "category": "Events",
                "tags": "BGMI 3.2, Update, Mecha, Poster, Theme, Jetpack, Krafton",
                "resolution": "4K",
                "width": 3840,
                "height": 2160,
                "orientation": "Landscape",
                "file_size": "6.9 MB",
                "file_format": "JPG",
                "view_count": 24800,
                "download_count": 9100,
                "featured": True,
                "source": "Krafton Development",
                "license": "Press Release"
            }
        ]

        inserted_count = 0
        for i, item in enumerate(assets):
            media_id = f"media_{uuid.uuid4().hex[:10]}"
            created_date = base_time + datetime.timedelta(days=i * 0.8, hours=i * 2)
            
            asset = MediaAsset(
                media_id=media_id,
                title=item["title"],
                description=item["description"],
                image_url=item["image_url"],
                thumbnail_url=item["thumbnail_url"],
                category=item["category"],
                tags=item["tags"],
                resolution=item["resolution"],
                width=item["width"],
                height=item["height"],
                orientation=item["orientation"],
                file_size=item["file_size"],
                file_format=item["file_format"],
                view_count=item["view_count"],
                download_count=item["download_count"],
                like_count=int(item["download_count"] * 0.4),
                featured=item["featured"],
                status="active",
                source=item["source"],
                license=item["license"],
                created_at=created_date,
                updated_at=created_date
            )
            db.add(asset)
            inserted_count += 1

        db.commit()
        print(f"[Seed Media] Successfully seeded {inserted_count} Pinterest-grade BGMI & PUBG Mobile media assets into DB!")

    except Exception as e:
        db.rollback()
        print(f"[Seed Media] Error during media seeding: {e}")
        raise e
    finally:
        db.close()

if __name__ == "__main__":
    seed_media()
